### PR TITLE
Support GridView's numColumn property and applyVisibility

### PR DESCRIPTION
**Pull request by BrandonTsai**
Also support get ids by DynamicView.getIdMap();
Therefore, user can get child view by findViewById(idMap.get("id_name").intValue());

### CODE REVIEW

**Comment by tsiougkosn** [comment]
Hi there,

It seems that some tests are failing due to your changes in the pull request.
Could you check on it ?

**Comment by BrandonTsai** [comment]
Hi,

I have committed the fix.
Thanks.

**Comment by tsiougkosn** [comment]
Hi there,

Thanks for checking and fix the failing test.
I have a comment. Please check it out.

Also it would be better to make a Pull Request per feature, eg you PR can be split in four PRs, one for changes in visibility, an other one for numColumns of GridView and the other two for ids and  background.

**Comment by tsiougkosn** [comment]
The PR is split by @BrandonTsai. so closing

**Pull request closed without merging**
